volumes:
  mysql-store-81:
  redis-store-72:

services:
  nginx-php-fpm-8.2:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./nginx-php-fpm-82/Dockerfile
    ports:
      - ${NGINX_PORT_1}:8009
      - ${NGINX_PORT_2}:8010
      - ${NGINX_PORT_3}:8014
      - ${NGINX_PORT_4}:8015
      - ${NGINX_PORT_5}:8080
    volumes:
      - ./nginx-php-fpm-82/tpl.d:/etc/nginx/tpl.d
      - ./nginx-php-fpm-82/general.conf:/etc/nginx/general.conf
      - ./nginx-php-fpm-82/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro

    depends_on:
      - mysql-81
      - redis-72
    networks:
      - backend

  mysql-81:
    container_name: ${MYSQL_81_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./mysql-81/Dockerfile
    ports:
      - ${MYSQL_HOST_PORT}:3306
    volumes:
      - type: volume
        source: mysql-store-81
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  redis-72:
    container_name: ${REDIS_72_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./redis-72/Dockerfile
    ports:
      - ${REDIS_HOST_PORT}:6379
    volumes:
      - redis-store-72:/data
      - ./redis-72/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
      
networks:
  backend:
    driver: bridge
