volumes:
  devops-mysql-store-81:
  devops-redis-store-72:

services:
  nginx-php-fpm-8.2:
    container_name: devops-nginx-php-fpm-82
    build:
      context: .
      dockerfile: ./nginx-php-fpm-82/Dockerfile
    ports:
      - 2009:8009
      - 2010:8010
      - 2014:8014
      - 2015:8015
      - 2080:8080
    volumes:
      - ./nginx-php-fpm-82/tpl.d:/etc/nginx/tpl.d
      - ./nginx-php-fpm-82/general.conf:/etc/nginx/general.conf
      - ./nginx-php-fpm-82/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro

    depends_on:
      - devops-mysql-81
      - devops-redis-72
    networks:
      - devops-backend

  devops-mysql-81:
    container_name: devops-mysql-81
    build:
      context: .
      dockerfile: ./mysql-81/Dockerfile
    ports:
      - 2306:3306
    volumes:
      - type: volume
        source: devops-mysql-store-81
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      MYSQL_ROOT_PASSWORD: Devops-Arisvn1369!
      MYSQL_DATABASE: gencode_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devops-backend

  devops-redis-72:
    container_name: devops-redis-72
    build:
      context: .
      dockerfile: ./redis-72/Dockerfile
    ports:
      - 2379:6379
    volumes:
      - devops-redis-store-72:/data
      - ./redis-72/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devops-backend
      
networks:
  devops-backend:
    driver: bridge
